"""Committed example run snapshots that ship with the app and are seeded on deploy.

Each `*.json` here is a full repopulation-run snapshot (nodes incl. grounded descriptions, weighted
edges, relevance, provenance) generated by the live discovery pipeline via scripts/build_example.py.
`seed.py` loads them idempotently so the deployed app always exposes the same selectable examples.
"""
