/**
 * GroundedDescription — provenance affordance for an AI-grounded node description (Phase 4).
 *
 * Lazy-fetches GET /api/node/description for a node and, when the description was generated by a
 * model AND cites evidence, renders a subtle "Grounded · cites N sources" disclosure that expands to
 * the exact evidence the model was allowed to use. Renders nothing for legacy (DynamoDB) `about`
 * text or nodes without evidence, so it is purely additive — existing nodes look unchanged.
 *
 * Aesthetic: monochrome, restrained, shadcn-native. CSS-only grid-rows height animation.
 */
import { useEffect, useState } from 'react';
import { Sparkles, ChevronDown } from 'lucide-react';
import { Skeleton } from '@/components/ui/skeleton';
import { fetchNodeDescription, type NodeDescription } from '@/services/dynamodb';

// Human labels for the evidence `kind` (see backend descriptions/retrieve.py).
const KIND_LABEL: Record<string, string> = {
  affiliation: 'Affiliation',
  topics: 'Research topics',
  paper: 'Publication',
  coauthor: 'Co-author',
  related: 'Related work',
  description: 'Self-description',
  pi: 'Principal investigator',
  areas: 'Research areas',
  member: 'Member',
};

/** Strip the provider prefix + promote tag for a compact model label (e.g. "gemini-2.5-flash-lite"). */
function modelLabel(model: string | null): string | null {
  if (!model || model === 'legacy_dynamodb') return null;
  const bare = model.startsWith('promoted:') ? model.slice('promoted:'.length) : model;
  return bare.includes('/') ? bare.split('/').pop()! : bare;
}

interface GroundedDescriptionProps {
  nodeId: string;
  /** Indent to align under a `ml-7` modal section (ResearcherModal). Lighter modals pass false. */
  inset?: boolean;
}

const GroundedDescription: React.FC<GroundedDescriptionProps> = ({ nodeId, inset = true }) => {
  const indent = inset ? 'ml-7' : '';
  const [data, setData] = useState<NodeDescription | null>(null);
  const [loading, setLoading] = useState(true);
  const [open, setOpen] = useState(false);

  useEffect(() => {
    let active = true;
    setLoading(true);
    setData(null);
    setOpen(false);
    fetchNodeDescription(nodeId)
      .then((d) => active && setData(d))
      .catch(() => active && setData(null))
      .finally(() => active && setLoading(false));
    return () => {
      active = false;
    };
  }, [nodeId]);

  if (loading) return <Skeleton className={`h-4 w-44 ${indent}`} />;

  const model = modelLabel(data?.description_model ?? null);
  const evidence = data?.evidence ?? [];
  if (!model || evidence.length === 0) return null; // legacy / ungrounded → nothing extra

  return (
    <div className={indent}>
      <button
        onClick={() => setOpen((o) => !o)}
        aria-expanded={open}
        className="inline-flex items-center gap-1.5 text-xs text-muted-foreground hover:text-foreground transition-colors"
      >
        <Sparkles className="w-3.5 h-3.5" />
        <span className="font-medium tracking-tight">Grounded</span>
        <span className="text-muted-foreground/60">
          · cites {evidence.length} {evidence.length === 1 ? 'source' : 'sources'}
        </span>
        <ChevronDown
          className={`w-3.5 h-3.5 transition-transform duration-200 ${open ? 'rotate-180' : ''}`}
        />
      </button>

      {/* grid-rows 1fr/0fr → smooth, content-aware height animation with no JS measuring */}
      <div
        className={`grid transition-all duration-300 ease-out ${
          open ? 'grid-rows-[1fr] opacity-100 mt-3' : 'grid-rows-[0fr] opacity-0'
        }`}
      >
        <div className="overflow-hidden">
          <ol className="space-y-2.5 border-l border-border pl-4">
            {evidence.map((item) => (
              <li key={item.id} className="flex gap-2.5 text-sm">
                <span className="mt-0.5 font-mono text-xs text-muted-foreground tabular-nums">
                  [{item.id}]
                </span>
                <span className="min-w-0">
                  <span className="block text-[11px] uppercase tracking-wider text-muted-foreground/70">
                    {KIND_LABEL[item.kind] ?? item.kind}
                  </span>
                  <span className="block text-foreground leading-snug">{item.text}</span>
                </span>
              </li>
            ))}
          </ol>
          <div className="mt-2.5 pl-4 text-[11px] text-muted-foreground/60">
            Generated by {model}, grounded only in the evidence above.
          </div>
        </div>
      </div>
    </div>
  );
};

export default GroundedDescription;
