"""Grounded node-description schema + validator (Phase 4) — the hallucination/injection backstop.

A description is generated by an LLM over UNTRUSTED evidence text (paper titles, scraped lab blurbs,
neighbour names). As with lab extraction (`lab_schema.py`), the model's output is DATA: we frame the
evidence as data, send no tools, and STRUCTURALLY validate the returned JSON here before it can touch
the graph. `validate` returns a `NodeDescription` only when the object matches the strict schema —
wrong types, missing required fields, or any extra/control key (e.g. an injected ``"tool_call"``)
yield ``None`` so the caller quarantines instead of trusting it.

Grounding ("no evidence -> no claim", AGENTS.md constraint 5) is enforced one layer up in
`descriptions/build_rows.py`: this module guarantees the SHAPE (a summary, a list of cited evidence
ids, a confidence); `build_rows` checks the cited ids actually resolve to evidence that was shown to
the model. Pure: no DB / network / LLM / clock.
"""
from __future__ import annotations

from dataclasses import dataclass

MAX_SUMMARY_CHARS = 1200


@dataclass(frozen=True)
class NodeDescription:
    """A validated, grounded description of one node.

    `evidence` is the set of evidence ids (1-based indices into the evidence list the prompt showed
    the model) the model claims ground the summary; `build_rows` verifies they resolve. `confidence`
    is the model's own 0..1 self-rating.
    """

    summary: str
    evidence: tuple[int, ...]
    confidence: float


# Strict JSON schema for OpenRouter `response_format`. `additionalProperties: false` is the injection
# backstop — any key the model adds beyond these three is rejected by `validate`.
DESCRIPTION_JSON_SCHEMA: dict = {
    "type": "object",
    "additionalProperties": False,
    "required": ["summary", "evidence", "confidence"],
    "properties": {
        "summary": {"type": "string", "minLength": 1, "maxLength": MAX_SUMMARY_CHARS},
        "evidence": {
            "type": "array",
            "items": {"type": "integer", "minimum": 1},
        },
        "confidence": {"type": "number", "minimum": 0, "maximum": 1},
    },
}

_ALLOWED_KEYS = frozenset(DESCRIPTION_JSON_SCHEMA["required"])


def validate(obj: object) -> NodeDescription | None:
    """Return a `NodeDescription` iff `obj` matches `DESCRIPTION_JSON_SCHEMA` exactly, else `None`.

    Rejects (-> None): non-dicts, missing required keys, ANY extra key (control/injection fields),
    a non-string/empty/over-long summary, an evidence list that isn't all positive ints, or a
    confidence outside 0..1 (or non-numeric). Booleans are not accepted as ints/floats.
    """
    if not isinstance(obj, dict):
        return None
    if set(obj.keys()) != _ALLOWED_KEYS:  # missing-required OR extra-key both fail here
        return None

    summary = obj["summary"]
    if not isinstance(summary, str):
        return None
    summary = summary.strip()
    if not summary or len(summary) > MAX_SUMMARY_CHARS:
        return None

    raw_evidence = obj["evidence"]
    if not isinstance(raw_evidence, list):
        return None
    evidence: list[int] = []
    for item in raw_evidence:
        # bool is a subclass of int — exclude it so `true` can't masquerade as an id.
        if isinstance(item, bool) or not isinstance(item, int) or item < 1:
            return None
        evidence.append(item)

    confidence = obj["confidence"]
    if isinstance(confidence, bool) or not isinstance(confidence, (int, float)):
        return None
    confidence = float(confidence)
    if not (0.0 <= confidence <= 1.0):
        return None

    # Dedupe + sort the cited ids for a deterministic, idempotent NodeDescription.
    return NodeDescription(
        summary=summary,
        evidence=tuple(sorted(set(evidence))),
        confidence=confidence,
    )
